services:
  tg-forecast:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-forecast-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
    env_file:
      - .env
    volumes:
      - .:/app:ro
      - ./images:/app/images
      - ./logs:/app/logs
    mem_limit: 256m
    mem_reservation: 128m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
